#!/bin/sh

help() {
    echo "Usage:":
    echo "  $0 [--noconfirm] foo [bar...]   - setup symlinked dotfiles for specified files and subdirectories"
    echo "  $0 [--noconfirm] --all          - setup symlinked dotfiles for all files and subdirectories"
    echo "  $0 --help                       - display this help message"
}

link() {
    find "$@" -path '.*' -prune -o \
        \( -path '*/*' -prune \
            -exec echo ln -ns "\"$PWD/{}\"" "\"$XDG_CONFIG_HOME/{}\"" ';' \
            -ok ln -ns "$PWD/{}" "$XDG_CONFIG_HOME/{}" ';' \
          -o \! -path '*/*' -type d \
            -exec echo mkdir -pv "\"$XDG_CONFIG_HOME/{}\"" ';' \
            -ok mkdir -pv "$XDG_CONFIG_HOME/{}" ';' \) -o \
        \( \! -path '*/*' -type f \
            -exec echo ln -ns "\"$PWD/{}\"" "\"$HOME/.{}\"" ';' \
            -ok ln -ns "$PWD/{}" "$HOME/.{}" ';' \)
    return $?
}

linknoconfirm() {
    find "$@" -path '.*' -prune -o \
        \( -path '*/*' -prune \
            -exec echo ln -ns "\"$PWD/{}\"" "\"$XDG_CONFIG_HOME/{}\"" ';' \
            -exec ln -ns "$PWD/{}" "$XDG_CONFIG_HOME/{}" ';' \
          -o \! -path '*/*' -type d \
            -exec echo mkdir -pv "\"$XDG_CONFIG_HOME/{}\"" ';' \
            -exec mkdir -pv "$XDG_CONFIG_HOME/{}" ';' \) -o \
        \( \! -path '*/*' -type f \
            -exec echo ln -ns "\"$PWD/{}\"" "\"$HOME/.{}\"" ';' \
            -exec ln -ns "$PWD/{}" "$HOME/.{}" ';' \)
    return $?
}

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}

for arg in "$@"; do
    shift
    [ "$arg" = "--noconfirm" ] && alias link=linknoconfirm && continue
    set -- "$@" "$arg"
done

case "$#" in
    "0") help; exit 1;;
    "1")
        case "$1" in
            "--help") help; exit 0;;
            "--all") link *; exit $?;;
        esac
esac

for arg in "$@"; do
    link "$arg"
done
