function () { # scope to keep local variables from bleeding out

if [[ $- == *i* ]] && [ -z "$TMUX" ] && type tmux > /dev/null; then
    # This is an interactive shell, and not already in tmux
    exec tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"
fi

source $ZDOTDIR/vi.zsh
source $ZDOTDIR/aliases.zsh
source $ZDOTDIR/bindkeys.zsh
source $ZDOTDIR/colors.zsh
source $ZDOTDIR/completion.zsh
source $ZDOTDIR/history.zsh
source $ZDOTDIR/options.zsh
source $ZDOTDIR/prompt.zsh

# External plugins
source $ZDOTDIR/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

}
