source $ZDOTDIR/vi.zsh
source $ZDOTDIR/aliases.zsh
source $ZDOTDIR/bindkeys.zsh
source $ZDOTDIR/completion.zsh
source $ZDOTDIR/history.zsh
source $ZDOTDIR/options.zsh
source $ZDOTDIR/prompt.zsh

# External plugins
source $ZDOTDIR/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
